version: '2'


services:


    web_video:
        restart: unless-stopped
        container_name: web.video
        build:
            context: .
        entrypoint: /app/project-video/docker/backend/entry-point/server-entrypoint.sh
        volumes:
            - backend_container_data:/app/project-video/
        ports:
            - 8000:8000
        environment:
            DEBUG: "True"
            CELERY_BROKER_URL: "redis://redis:6379/0"
            CELERY_RESULT_BACKEND: "redis://redis:6379/0"
            DJANGO_DB: video
            MYSQL_HOST: mysql.video
            MYSQL_NAME: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: password
            MYSQL_PORT: 3306
        depends_on:
            - mysql


    redis:
        image: redis:6.0-alpine
        container_name: redis.video
        ports:
        - 6379:6379

    mysql:
        # image:  
        image:   mysql:8.0
        container_name: 'mysql.video'
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: video
        ports:
          - 3306:3306
        volumes:
          - mysql-container-data:/var/lib/mysql


volumes:
    mysql-container-data:
    backend_container_data:


